# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email_subject', models.CharField(default='Happy birthday from Dr. {0}', max_length=256)),
                ('email_body', models.TextField(default='Dear [first name] [last name],\n\nHappy birthday!\n\nSincerely,\nDr. {0}')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('birthday', models.DateTimeField()),
                ('send_email', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drchrono_birthday.Doctor')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
