# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
